version: "3.7"

services:
  # Web UI
  miredibaseux:
    build:
      context: ./mbux
      target: "production-stage"
    container_name: miredibaseux
    volumes:
      - ./mbux:/app
    ports:
      - "8080:80"
    depends_on:
      - miredibaseapi
    restart: always

  # RESTful API
  miredibaseapi:
    build:
      context: ./mbapi
    container_name: miredibaseapi
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_ROOT_USERNAME}
      MONGO_PASS: ${MONGO_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      ROOT_PATH: /miredibaseapi
    volumes:
      - ./mbapi:/mbapi
    ports:
      - "9001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 
    depends_on:
      - miredibasemongo
    restart: always

  # Database
  miredibasemongo:
    image: mongo
    container_name: miredibasemongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - ./mbdata:/data/db
    ports:
      - "27017:27017"
    restart: always
  
  # Database data
  miredibasemongo-seed:
    image: mongo 
    volumes:
      - ./data:/data
    command: mongorestore --drop --port ${MONGO_PORT} --host ${MONGO_HOST} -u ${MONGO_ROOT_USERNAME} -p ${MONGO_ROOT_PASSWORD} --authenticationDatabase 'admin' -d ${MONGO_DB} /data/
      
volumes:
    mbdata:
